/**
 * PDF export — uses browser print dialog with a styled HTML document.
 * Falls back to downloading a .txt file if print is unavailable.
 */

export async function exportToPDF(markdown: string, incidentId: string): Promise<void> {
  const html = buildHTML(markdown, incidentId);

  // Open in a new window and trigger print
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    // Wait for render then print
    setTimeout(() => {
      printWindow.print();
    }, 500);
  } else {
    // Fallback: download as .txt
    const blob = new Blob([markdown], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${incidentId}-summary.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }
}

function buildHTML(markdown: string, incidentId: string): string {
  const date = new Date().toISOString().split("T")[0];
  return `<!DOCTYPE html>
<html>
<head>
  <title>Incident ${incidentId} Summary</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #333; }
    h1 { font-size: 24px; border-bottom: 2px solid #333; padding-bottom: 8px; }
    h2 { font-size: 18px; margin-top: 24px; color: #555; }
    pre { white-space: pre-wrap; font-family: inherit; line-height: 1.6; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <pre>${escapeHTML(markdown)}</pre>
  <div class="footer">
    Generated by Agora Incident Commander on ${date}
  </div>
</body>
</html>`;
}

function escapeHTML(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
